// <auto-generated />
namespace MVCBog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ads1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ads1));
        
        string IMigrationMetadata.Id
        {
            get { return "201608311430305_ads1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
